language: python
sudo: required

services:
  - docker

before_install:
  - docker version
  - docker build -t ptdorf/ping .

script:
  - docker run ptdorf/ping google.com

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ptdorf/ping;
    fi

env:
  - secure: "Ie9P42G0MwVjT6jQRg5+etg8wuCCusWiyziaLpUS3OGaeEeNvQIpoybeJCTVxGmEhJ7DnMk3+Aqmkh8KbcX462gkDEqzkintD8TbDlUzxe1Hlw8TPpHlc7Rj/60dvj9xat4cR1vM+of57fuSXeveytvaODpEWmJCArYqJiO2b1OKiFNkaXmzaer48yS2YM0EBoxGOOn+iBVSr0/05GmPa/6wCmk8wMTZL8ywoBO0u5VRs6oPeRA6zu72zP47RPyxezAgWVyh3pEym11t2lNkWSk0RB4uMB7ciZkEnGpSV74i0P5CjPXFl8pvIyz1J3XJS69u9uELvNdGyMMnPWxcLad7ug9zSjrFzfups6TkoZj0xgmAMgUvNhW2jpks/7XyyJZ6i9TLNcIkGveXrfEt3YY+3lds/6jinh84TG3sSWalNPr4yhVje+8hzPGjG9LR9fRgnQnwYtgvn3LZjpVfsViz/51PVOtnpt9GYHK6by8jvX+koFOTD+TMxscU27phybsu/pFtJgUJ56j3NEEkqij0tcRp2R6aBNKHB22cHpGzqqa85ZZRpmUL3m+VH9Tv/F/c2iQeT8uoZEGaucMQO3TxPR25CtsB4oYordhOO22d/w9flWUx1oXnXDkI4ae4RaAD6zMmmm3x/4tVUmAc99v8bO3CizpCuCTi4w08/Cw="
  - secure: "g6hicpL634F6A3LtXkpXzw51sd4r9GgQhju6FfOiCDaueTpH+HJr9BFHE9ULnlyQeZRq+qVQ/aV1kSGSaCSv7XYTfmtwNphb+jgKJbUk3x/0Eroi0u705b+pPApj9Eqrl3KvpLyUUMUnCKfEf+oZ/SNvCo0wUh60Eabq/fBWHLJolnqQys2BBRuvzFOjRQC2ZTrx0Kwi00evqSVnazOCYD51OT9EiCuTGXOxKeaeFlH/8TSIbA2bWI8lKUwjEI+4pXKAR6QAY/MKKFdbOWK0EZHU7IrLSq2GBhUN4dVx1BtiiXRuP9Q5C4BEj7ZcGIqyqqn2OauGwSx36qifvRuXAMTrncTOW0W7q51GOKa1erj9eF/DmPuhLzWoLps3ynopPe4Od2uX0FQRSoQuiUVyiCGogYKR0b1vc93NtIO39sVU+hBxCda0LZdgeDev6aTKepcs1Y4DzQGfTpzt5O4M7J82Z7GdlCCsyrgpoX58QF0C6KZCby1Gq/pmk7YpnqQHzVWxofFtrlE/cgiLpaOsVr67/XUJK2daig/EXXFgT2I1nT31/gn8suT2bwQ68tStdB8AQkewt5ECEN+JNfXY3l18jxm7K76uUw44kGPXbJzX+obnLwuqUU968MVVNrwQVlPD149AbHmkT1gxnYwehh/hETj9n7BD+kehLMovVC4="
