language: python
sudo: required
services:
- docker
before_install:
- docker version
- docker build -t ptdorf/ping .
script:
- docker run ptdorf/ping google.com
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push ptdorf/ping; fi
env:
  secure: NBgUXIOUwsL6uHxN1aATEtgAGVm0JcLZfcKRQx8Hg/SPUSB948U03NeQLe0ewXsW8Z18DUgCn4j5BwqziL9Mz9Dk39h/mVLEh8WBkA7Vv2B2L1+wFVx/3s1yvW4Puz4jU7I4uWu3dFmj9cwh7t/GiGpN/3YKLs7BDEcV8uE5IR9UE8WVWtoVSK3PW7QhpCZcFd3Lic19WziN0eE8zK2/gazdGf5nK6Ri93gKz33SYy4lgotzd2rNWEwC3XwkaogtC2qTHfpSIm+z0wSE/J3akBNt4Q1Ij+Iz8JjXFV0uYmTbbBdJqql4tWE7UMLqmaBbOYafM+HjsgmsrwAtXizrJMktCiRk+F6dyqp6R+QrRc6OUw/CpYYoP5wSq0/TB0Ccexe0SP1AKYv+0T8dvWZqDP9/OrfLP7oLL70LTNBbMX3z7WJ4pbzAcrOTN620c8m1RX2KZgif1s7SO9cCscQqiV/w+Df0KN2wN1fGNPuevInxZpp5syKSPqxGcwL234VpxtLreMFojfFg9gEJJ7cHKg4UkZDjuRrkbNmxrrCtMKjouLywnt5TmtZDnPBgkfX9rbPEGMsEUyyNYHs7mMgeVNnVD+m5VjgyEJcqWdvb3UVCgmTAqQE2t6LiggrrQxbU5VGajkks4cYdq9C5lW/DaKwDcDd5IYyrY/oPUHyRVkI=
  matrix:
    secure: QUE8k5NNnM2euCObT2+LHb5ZeW+aieIFEoWCbnAf8CeeYHQ+YX1G+F4fMii2Bv7gg55b4sZ3aFhdINCkSBVq5rJNFi7f0Hja9GuiPef0Dlcj43CmDkGKwXC21Cu1Z0TxEdbAeK/m31BWwB+V1B7SGa/A4Ay45QnLppbJMqRXklTpMM1JkNwa8DuiU2E0GOCQSMeziMQ/PmDPP0JyttxDsh7rH5HEu4dQqLJCEpYSqh2k+vl+w4pmTPVJAML0EQs1DhFXScXWrrXkiGRNb33ylqLefScklmhlaa4ddKbzTEc9YVJ7J19BbKrSwX9j/Qd4UrlWNJOH4VM1kwAsJ5hzzcMm1k+77jnzwFKoW4S/YO9mDJ7E7au7hPYhu9Ih05SgXB2Ccb7Vp7fgdOogj6mUGzsKNdU6shOPMVeH1pOZ6GAk0LvTavVn++lAoAKS4xjTeT3IWQ7VnQQ9FpnUoxgwEVxuqVtlFpcaknwPUcCu5AtAE+9COxUyunuBDjhJUzxSTazUxvrkZodOzc8daDLBW9/njZpCvdauO37jQxP9oRNRcNg0pzjeWEpDEIdK+8YjYlQkvoD07mEVDU86FJTveFXIibds5ZnNhYHEY/eM2UFLs5lLWn/H3EMANaOnJmMMX+gAjcsdajRsZ9c88HRoLl3s2PhleqHhr6bxiF0aPwQ=
