language: python
sudo: required

services:
  - docker

env:
  global:
    - secure: "dfMubLN9014YiVwUA14O9BPdBtS8ox2oVpP1nAYm9yU9nh5+mRPIJlUP+DCqP7fcZipt1PowheKiHaz5Kkan5bYTA6s4ADuPXsPchWJmp5+Q55DwJpY5m6NIL6iL6fns0sCujyi2XdIIbEfuwC46TzHfsZ7hH79pzTo2lcB5rBdtsYMKGr9/MRJiJm2TU1IpgDENe/fnq82GcMCL3yhUqMo1mm++bgbxqWx1NWucGMwqp3ugsT7Xz3gSAPUXE/QyKR4eVrThbHzNTgx2qNxsQpq8ej2Y1NElzto2MnKDStud8ppNkPX/qEjO46IhC3wXWge02wD3sNw7GUQX8yqxqMY87uu1Ejts4o8wu6gf5pXXVHWQqvx7oWMoJGZQeXEf6GSa8M7VnZij8C/JdzwQMSvWlHrvqJ6HZO0ZDFzSZZ+jD/o5V3aNO8NTD7/h7rzJq20U3Co+FS8x3Wun1Qvtj0V9dUtjNVYaYDZvKZ5XDJ0nwpM2QKtV6cVAWmyonmkdbTA8S4QOXtXXkR1KNPSNMOgT9Ce2+jhTXTRdick+IVUwOkbqsVBFB9h6FiVYQx9KasulegFhybwjS96j3DEzbVUkHDRG9ZZDbBY2RxcdYczWnHNli+fSs6J2oWkk5V/csFFXB7BMuVgn7Cx1WDghUwzeFaR+slt9pBjKkehzMHU="
    - secure: "ZLSJOH7T2LDIWXy02JY0DS26YXPHee4D177Ei/XbfKsVFczNpvpYgdKsFUghxeToSCAn8hAEEPNOFu9Uea9rx4tb5FSC3P6/lpv2bk4B3mc+oHJTGTrlbone5jJYqXJnBSiDx6cuR9BZkAh8XjFiHe+ZkUTYN9Ct/4s8dhcLaQiTdLKVxBz+MXPEJOZCBbompkc3L9Dkl8AofR9jX7q7Vb/u/YPBgwAlnGm0QAQPr3T9odxMrdBzpRpO3LEvQJMStJ8P26d0qgRmsVn1g1q3nx3p7Owe1oC5AcP+BI/0qVcdV8OmjfxZxeN8DuV/oZe9X5pWEJXJvBd6K9Li58mi5nP4AxUM3fNljqNtKKOcDxrocS/XVi00WrE2Ltl4ioLrmB3gXsmBBjiYzH/sIOHFX336KAlaKOxG2F6EdL8XQNHcMehiYDyI0bS+CUS3ZMx9ecVNwfw9kuXDAmFWB1S9s4ygz5d2/RlPAPG7vKWEU+OEe+M+sb3OSqmu6VTTGfV/9vF8D2sEHaJIFcncBlNAcmMhyF5+SBMdKOJHHy4/e50RjvuvnRa/EIBUgwK+0dNLwR4AkekMzKQAE8y2X7vROejlIbBKDGQhgURDY06nwPgGibrMUJ+8Kdl/v6pkjFkVXlYXaQWnvdkz6TtQXOugydbnTvtm1wtYkSKdpXyz5ps="

before_install:
  - env
  - docker version
  - docker build -t ping .

script:
  - docker run ping google.com

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    DOCKER_TAG="ptdorf/ping:${TRAVIS_TAG:-latest}";

    if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "Tagging image with ${DOCKER_TAG}.";
    docker tag ping ${DOCKER_TAG};
    docker push ${DOCKER_TAG};
    fi

    if [ "$TRAVIS_TAG" != "" ]; then
    echo "Tagging image with ${DOCKER_TAG}.";
    docker tag ping ${DOCKER_TAG};
    docker push ${DOCKER_TAG};
    fi
