language: python
sudo: required

services:
  - docker

before_install:
  - docker version
  - docker build -t ptdorf/ping .

script:
  - docker run ptdorf/ping google.com

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ptdorf/ping;
    fi
