#!/usr/bin/env bash

docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
DOCKER_TAG="ptdorf/ping:${TRAVIS_TAG:-latest}"

echo "==> Travis environment"
env | grep TRAVIS

echo "==> Docker environment"
env | grep DOCKER | grep -v DOCKER_PASSWORD

if [ "$TRAVIS_BRANCH" == "master" ]
then
  echo "==> Tagging image with ${DOCKER_TAG}."
  docker tag ping ${DOCKER_TAG}
  docker push ${DOCKER_TAG}
fi

if [ "$TRAVIS_TAG" != "" ]
then
  echo "==> Tagging image with ${DOCKER_TAG}."
  docker tag ping ${DOCKER_TAG}
  docker push ${DOCKER_TAG}
fi
